data: '/home/linjunyang/multilabel_rcv/data/'
logF: 'experiments/rcv/'
epoch: 20
batch_size: 64
optim: 'adam'
cell: 'lstm'
attention: 'luong_gate'
learning_rate: 0.0003
max_grad_norm: 10
learning_rate_decay: 0.5
start_decay_at: 1
emb_size: 512
hidden_size: 512
dec_num_layers: 2
enc_num_layers: 2
bidirectional: True
dropout: 0.2
max_time_step: 8
eval_interval: 500
save_interval: 1000
unk: False
schedule: False
schesamp: False
length_norm: True
metrics: ['hamming_loss', 'macro_f1', 'micro_f1']
shared_vocab: False
beam_size: 5
dilated: True